bootstrap: Major refactoring
Now symlinks all files that begin with `symlink.`.
Also works with `symlink`ing direrctories.

Any symlink files that are more than 1 directory deep have those extra
directories created.
e.g. `ssh/ssh/symlink.rc` will create `~/ssh/` and then symlink
`symlink.rc` to `~/ssh/rc`.

Any extra symlinking should be done with a `link.sh` script in the
appropriate directory.

Moved symlink stuff into `script/link_dots`.

Should also display syntax correctly on github

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,10 +1,27 @@
-# vim: ft=sh
 #!/usr/bin/env bash
+# vim: ft=sh
 #
 # bootstrap installs things.
 # https://github.com/holman/dotfiles
 
 # NOTE: returning 0 == True, returning 1 == False
+
+UPDATE_PACMAN=
+POSITIONAL=()
+while [[ "$#" -gt 0 ]]; do
+  key="$1"
+  case $key in
+    -u|--update)
+      UPDATE_PACMAN=1
+      shift
+    ;;
+    *)
+      POSITIONAL+=("$1")
+      shift
+    ;;
+  esac
+done
+set -- "${POSITIONAL[@]}" # restore positional parameters
 
 if [ -z "$XDG_CONFIG_HOME"]; then
   export XDG_CONFIG_HOME="$HOME/.config"
@@ -81,120 +98,38 @@ fail () {
   exit
 }
 
-link_file () {
-  local src=$1 dst=$2
-
-  local overwrite= backup= skip=
-  local action=
-
-  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
+install_pacman() {
+  # If we're on a Mac, let's install and setup homebrew.
+  if isOSX
   then
-
-    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
-    then
-
-      local currentSrc="$(readlink $dst)"
-
-      if [ "$currentSrc" == "$src" ]
+    if ! hasCommand brew; then
+      info "installing Mac dependencies"
+      if source os/mac.sh >/tmp/dotfiles-dot 2>&1
       then
-
-        skip=true;
-
+        success "dependencies installed"
       else
-
-        user "File already exists: $(basename "$src"), what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
-        read -n 1 action
-
-        case "$action" in
-          o )
-            overwrite=true;;
-          O )
-            overwrite_all=true;;
-          b )
-            backup=true;;
-          B )
-            backup_all=true;;
-          s )
-            skip=true;;
-          S )
-            skip_all=true;;
-          * )
-            ;;
-        esac
-
+        fail "error installing dependencies"
       fi
-
     fi
-
-    overwrite=${overwrite:-$overwrite_all}
-    backup=${backup:-$backup_all}
-    skip=${skip:-$skip_all}
-
-    if [ "$overwrite" == "true" ]
-    then
-      rm -rf "$dst"
-      success "removed $dst"
-    fi
-
-    if [ "$backup" == "true" ]
-    then
-      mv "$dst" "${dst}.backup"
-      success "moved $dst to ${dst}.backup"
-    fi
-
-    if [ "$skip" == "true" ]
-    then
-      success "skipped $src"
-    fi
-  fi
-
-  if [ "$skip" != "true" ]  # "false" or empty
+  # If we're on linux, let's update apt-get
+  elif isLinux
   then
-    ln -s "$1" "$2"
-    success "linked $1 to $2"
-  fi
-}
-
-install_dotfiles () {
-  info 'installing dotfiles'
-
-  local overwrite_all=false backup_all=false skip_all=false
-
-  for src in $(find "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink')
-  do
-    dst="$HOME/$(basename "${src%.*}")"
-    link_file "$src" "$dst"
-  done
-}
-
-
-# If we're on a Mac, let's install and setup homebrew.
-if isOSX
-then
-  if ! hasCommand brew; then
-    info "installing Mac dependencies"
-    if source os/mac.sh >/tmp/dotfiles-dot 2>&1
+    info "installing Linux dependencies"
+    if source os/linux.sh
     then
       success "dependencies installed"
     else
       fail "error installing dependencies"
     fi
   fi
-# If we're on linux, let's update apt-get
-elif isLinux
-then
-  info "installing Linux dependencies"
-  if source os/linux.sh
-  then
-    success "dependencies installed"
-  else
-    fail "error installing dependencies"
-  fi
-fi
+}
 
-install_dotfiles
-source "$DOTFILES_ROOT"/script/install
-source "$DOTFILES_ROOT"/script/postinstall
+if [ -n "$UPDATE_PACMAN" ]; then
+  install_pacman
+fi
+source "$DOTFILES_ROOT"/script/link_dots
+# source "$DOTFILES_ROOT"/script/install
+# source "$DOTFILES_ROOT"/script/postinstall
 
 
 echo ''
